[package]
name = "approximate_seq"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustfft = "6.0.1"
num-complex = "0.4"
num-traits = "0.2.14"
rand = "0.8.4"
mathru = "0.9.1"
